// <auto-generated />
using System;
using AppEmit.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppEmit.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525193111_AlignConceptionModel")]
    partial class AlignConceptionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppEmit.API.Entities.Creneau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Creneaux");
                });

            modelBuilder.Entity("AppEmit.API.Entities.DemandeEchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CibleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateReponse")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DemandeurId")
                        .HasColumnType("integer");

                    b.Property<string>("Motif")
                        .HasColumnType("text");

                    b.Property<int>("SeanceCibleId")
                        .HasColumnType("integer");

                    b.Property<int>("SeanceDemandeurId")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CibleId");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("SeanceCibleId");

                    b.HasIndex("SeanceDemandeurId");

                    b.ToTable("DemandesEchange");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrganisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisateurId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("AppEmit.API.Entities.ExceptionPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Motif")
                        .HasColumnType("text");

                    b.Property<int?>("NouvelleSalleId")
                        .HasColumnType("integer");

                    b.Property<int>("SeanceCoursId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeException")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SeanceCoursId");

                    b.ToTable("ExceptionsPlanning");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnvoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EstLu")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("IX_Notifications_UtilisateurId");

                    b.HasIndex("UtilisateurId", "DateEnvoi")
                        .HasDatabaseName("IX_Notifications_UtilisateurId_DateEnvoi");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AppEmit.API.Entities.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MethodePaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Parcours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FiliereId");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvenementId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.Property<string>("Session")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.HasIndex("SalleId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("CodeSalle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Equipements")
                        .HasColumnType("text");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("AppEmit.API.Entities.SeanceCours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CouleurAffichage")
                        .HasColumnType("text");

                    b.Property<int>("CreneauId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDebutAnnee")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFinAnnee")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("boolean");

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer");

                    b.Property<int?>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParcoursId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesseurId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreneauId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("ParcoursId");

                    b.HasIndex("ProfesseurId");

                    b.HasIndex("SalleId");

                    b.ToTable("SeancesCours");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Matricule")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NiveauId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("RoleUtilisateur", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateursId")
                        .HasColumnType("integer");

                    b.HasKey("RolesId", "UtilisateursId");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("RoleUtilisateur");
                });

            modelBuilder.Entity("AppEmit.API.Entities.DemandeEchange", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Utilisateur", "Cible")
                        .WithMany()
                        .HasForeignKey("CibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Utilisateur", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.SeanceCours", "SeanceCible")
                        .WithMany()
                        .HasForeignKey("SeanceCibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.SeanceCours", "SeanceDemandeur")
                        .WithMany()
                        .HasForeignKey("SeanceDemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cible");

                    b.Navigation("Demandeur");

                    b.Navigation("SeanceCible");

                    b.Navigation("SeanceDemandeur");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Evenement", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Utilisateur", "Organisateur")
                        .WithMany("EvenementsOrganises")
                        .HasForeignKey("OrganisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisateur");
                });

            modelBuilder.Entity("AppEmit.API.Entities.ExceptionPlanning", b =>
                {
                    b.HasOne("AppEmit.API.Entities.SeanceCours", "SeanceOriginale")
                        .WithMany("Exceptions")
                        .HasForeignKey("SeanceCoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeanceOriginale");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Niveau", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Parcours", "Parcours")
                        .WithMany("Niveaux")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Notification", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Paiement", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Reservation", "Reservation")
                        .WithMany("Paiements")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Parcours", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Filiere", "Filiere")
                        .WithMany("Parcours")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Reservation", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Evenement", "Evenement")
                        .WithMany("Reservations")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evenement");

                    b.Navigation("Salle");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AppEmit.API.Entities.SeanceCours", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Creneau", "Creneau")
                        .WithMany()
                        .HasForeignKey("CreneauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Niveau", "Niveau")
                        .WithMany("Seances")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppEmit.API.Entities.Parcours", "Parcours")
                        .WithMany()
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppEmit.API.Entities.Utilisateur", "Professeur")
                        .WithMany("SeancesAnimees")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creneau");

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Parcours");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Utilisateur", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Niveau", "Niveau")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUtilisateur", b =>
                {
                    b.HasOne("AppEmit.API.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.API.Entities.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppEmit.API.Entities.Evenement", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Filiere", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Niveau", b =>
                {
                    b.Navigation("Seances");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Parcours", b =>
                {
                    b.Navigation("Niveaux");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Reservation", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Salle", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("AppEmit.API.Entities.SeanceCours", b =>
                {
                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("AppEmit.API.Entities.Utilisateur", b =>
                {
                    b.Navigation("EvenementsOrganises");

                    b.Navigation("Reservations");

                    b.Navigation("SeancesAnimees");
                });
#pragma warning restore 612, 618
        }
    }
}
