// <auto-generated />
using System;
using AppEmit.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppEmit.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502211217_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppEmit.Entities.Creneau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Creneaux");
                });

            modelBuilder.Entity("AppEmit.Entities.EvenementReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePrecise")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DemandeurId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("SalleId");

                    b.ToTable("EvenementReservations");
                });

            modelBuilder.Entity("AppEmit.Entities.ExceptionPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NouvelleSalleId")
                        .HasColumnType("integer");

                    b.Property<int>("SeanceCoursId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeException")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NouvelleSalleId");

                    b.HasIndex("SeanceCoursId");

                    b.ToTable("ExceptionsPlanning");
                });

            modelBuilder.Entity("AppEmit.Entities.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("AppEmit.Entities.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("AppEmit.Entities.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("AppEmit.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLu")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AppEmit.Entities.Parcours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FiliereId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FiliereId");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("AppEmit.Entities.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("AppEmit.Entities.SeanceCours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CouleurAffichage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreneauId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDebutAnnee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFinAnnee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstTermine")
                        .HasColumnType("boolean");

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreneauId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("ProfId");

                    b.HasIndex("SalleId");

                    b.ToTable("SeancesCours");
                });

            modelBuilder.Entity("AppEmit.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NiveauId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("AppEmit.Entities.EvenementReservation", b =>
                {
                    b.HasOne("AppEmit.Entities.Utilisateur", "Demandeur")
                        .WithMany("EvenementReservations")
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.Entities.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demandeur");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("AppEmit.Entities.ExceptionPlanning", b =>
                {
                    b.HasOne("AppEmit.Entities.Salle", "NouvelleSalle")
                        .WithMany()
                        .HasForeignKey("NouvelleSalleId");

                    b.HasOne("AppEmit.Entities.SeanceCours", "SeanceCours")
                        .WithMany()
                        .HasForeignKey("SeanceCoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NouvelleSalle");

                    b.Navigation("SeanceCours");
                });

            modelBuilder.Entity("AppEmit.Entities.Niveau", b =>
                {
                    b.HasOne("AppEmit.Entities.Parcours", "Parcours")
                        .WithMany()
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("AppEmit.Entities.Notification", b =>
                {
                    b.HasOne("AppEmit.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AppEmit.Entities.Parcours", b =>
                {
                    b.HasOne("AppEmit.Entities.Filiere", "Filiere")
                        .WithMany("Parcours")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("AppEmit.Entities.SeanceCours", b =>
                {
                    b.HasOne("AppEmit.Entities.Creneau", "Creneau")
                        .WithMany("Seances")
                        .HasForeignKey("CreneauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.Entities.Matiere", "Matiere")
                        .WithMany("Seances")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.Entities.Niveau", "Niveau")
                        .WithMany("Seances")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEmit.Entities.Utilisateur", "Prof")
                        .WithMany("Seances")
                        .HasForeignKey("ProfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEmit.Entities.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creneau");

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Prof");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("AppEmit.Entities.Utilisateur", b =>
                {
                    b.HasOne("AppEmit.Entities.Niveau", "Niveau")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("NiveauId");

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("AppEmit.Entities.Creneau", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("AppEmit.Entities.Filiere", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("AppEmit.Entities.Matiere", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("AppEmit.Entities.Niveau", b =>
                {
                    b.Navigation("Seances");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("AppEmit.Entities.Salle", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("AppEmit.Entities.Utilisateur", b =>
                {
                    b.Navigation("EvenementReservations");

                    b.Navigation("Notifications");

                    b.Navigation("Seances");
                });
#pragma warning restore 612, 618
        }
    }
}
